name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_WORKSPACE: dev
  AWS_REGION: eu-central-1


jobs:
  terraform:
    name: 'Terraform Infrastructure Deployment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #aws-region: ${{ secrets.AWS_REGION }}
        aws-region: $AWS_REGION 


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      run: terraform init

    - name: Select/Create Terraform workspace
      run: |
        terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

    - name: Terraform Plan
      run: terraform plan -var="region=eu-central-1"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var="region=eu-central-1"
